### ISSUE TITLE
Text mesh not working

### ISSUE THREAD

**Issue by sachin5590** [makimenko/angular-template-for-threejs#204] opened 2020-03-04 09:53 UTC
## Steps
1. For static data text mesh works, but if the data comes from api, and I am updating data after a fixed interval of time. Then text mesh only display for the first time, for subsequent calls it does not display the result. I am using text mesh inside ngFor and even if the no of text mesh, it does not update.

## Actual Result
Should display

## Expected Result
Not displaying

**Comment by makimenko** [comment] 2020-03-17 14:57
Could you please check/fix link provided in the issue?

Error:
![image](https://user-images.githubusercontent.com/11466819/76868976-4fa41280-6870-11ea-8c52-5896bf0b2e7a.png)

**Comment by sachin5590** [comment] 2020-03-19 09:57
Hi, I have updated the question.

**Comment by makimenko** [comment] 2020-09-16 08:01
Related / Duplicate of https://github.com/makimenko/angular-template-for-threejs/issues/168

**Closed by makimenko** 2020-09-16 08:01 UTC
